name: IceyPlayer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ">=3.10.0"
  flutter: 3.38.6 # update `.fvmrc` config

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  liquid_glass_easy: ^1.1.1
  animated_gradient_background: ^0.0.1
  open_app:
    path: plugins/open_app
  async: ^2.13.0
  audio_metadata_reader:
    path: plugins/audio_metadata_reader
  audio_query:
    path: plugins/audio_query
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  animated_toggle_switch: ^0.8.5
  blur: ^4.0.2
  bottom_sheet: ^4.0.4
  brotli: ^0.6.0
  chinese_font_library: ^1.2.0
  common_utils: ^2.1.0
  device_info_plus: ^12.2.0
  dio: ^5.9.0
  dio_http2_adapter: ^2.5.3
  easy_refresh: ^3.4.0
  event_bus: ^2.0.1
  executor: ^2.2.5
  extended_image: ^10.0.1
  filesize: ^2.0.1
  flex_seed_scheme: ^3.6.1
  flutter_app_minimizer_plus: ^1.0.2
  flutter_displaymode: ^0.7.0
  flutter_native_splash: ^2.4.7
  flutter_screenutil: ^5.9.3
  flutter_sficon: ^1.2.1
  fluttertoast: ^9.0.0
  go_router:
  go_transitions: ^0.8.3
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.2.1
  just_audio: ^0.10.5
  keframe: ^3.0.0
  logger: ^2.6.2
  lyric:
    path: plugins/lyric
  mime_type: ^1.0.1
  package_info_plus: ^9.0.0
  permission_handler: ^12.0.1
  pinyin: ^3.3.0
  rxdart: ^0.28.0
  scrollview_observer: ^1.26.2
  sliver_tools: ^0.2.12
  signals: ^6.2.0
  signals_flutter: ^6.2.0
  super_sliver_list:
    path: plugins/super_sliver_list
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  visibility_detector: ^0.4.0+2
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

