name: IceyPlayer
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.11+12

environment:
  sdk: ">=3.10.0"
  flutter: 3.38.6 # update `.fvmrc` config

dependencies:
  flutter:
    sdk: flutter

  ## 音频
  audio_metadata_reader:
    path: plugins/audio_metadata_reader
  audio_query:
    path: plugins/audio_query
  audio_service: ^0.18.18
  audio_session: ^0.2.2
  just_audio: ^0.10.5
  lyric:
    path: plugins/lyric

  ## UI
  animated_gradient_background: ^0.0.1
  animated_toggle_switch: ^0.8.7
  blur: ^4.0.2
  easy_refresh: ^3.4.0
  flex_seed_scheme: ^4.0.1
  flutter_lyric: ^3.0.2
  flutter_sficon: ^1.2.1
  fluentui_system_icons: ^1.1.273
  keframe: ^3.0.0
  liquid_glass_widgets: ^0.2.1-dev.7
  scrollview_observer: ^1.26.2
  sliver_tools: ^0.2.12
  super_sliver_list:
    path: plugins/super_sliver_list
  visibility_detector: ^0.4.0+2

  ## 存储
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3

  ## 对话框等
  bottom_sheet: ^4.0.4
  fluttertoast: ^9.0.0

  ## app跳转
  open_app:
    path: plugins/open_app
  url_launcher: ^6.3.2

  ## 高帧率
  flutter_displaymode: ^0.7.0

  ## 开屏
  flutter_native_splash: ^2.4.7

  ## 路由
  go_router: ^17.0.1
  go_transitions: ^0.8.3

  ## 权限
  permission_handler: ^12.0.1

  ## 日志
  catcher_2: ^2.1.5
  logger: ^2.6.2

  ## 设备信息
  device_info_plus: ^12.3.0

  ## 设备控制
  flutter_app_minimizer_plus: ^1.0.2
  wakelock_plus: ^1.4.0

  ## 事件管理
  event_bus: ^2.0.1

  ## 图片
  extended_image: ^10.0.1
  image_gallery_saver_plus: ^4.0.1
  image_picker: ^1.2.1

  ## 小工具
  async: ^2.13.0
  common_utils: ^2.1.0
  executor: ^2.2.5
  filesize: ^2.0.1
  mime_type: ^1.0.1
  pinyin: ^3.3.0
  uuid: ^4.5.2

  ## 网络
  brotli: ^0.6.0
  dio: ^5.9.0
  dio_http2_adapter: ^2.5.3

  ## 状态管理
  signals: ^6.3.0
  signals_flutter: ^6.3.0

  ## 字体
  chinese_font_library: ^1.2.0

dependency_overrides:
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

